# Generated by Django 5.1.3 on 2024-11-19 14:20

import django.db.models.deletion
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_sell', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('price_offer', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('ratings', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='images/imaged_default/images_d.png', upload_to=product.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='images/imaged_default/images_d.png', upload_to=product.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.product')),
            ],
        ),
    ]
